version: "3.8"

services:
  cert-generator:
    image: node:latest
    container_name: cert-generator
    restart: "no"
    volumes:
      - cert:/usr/src/certs
    command: sh -c "npm install -g web-push && \
      openssl req -nodes -new -x509 -keyout /usr/src/certs/key.pem -out /usr/src/certs/cert.pem -days 365 -subj '/C=HK/ST=Hong Kong/O=CU Later' && \
      npx web-push generate-vapid-keys --json > /usr/src/certs/webPushKeys.json"

  app:
    image: node:latest
    container_name: cu-later-app
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./app:/usr/src/app
      - cert:/usr/src/certs
    environment:
      - SSL_KEY=/usr/src/certs/key.pem
      - SSL_CERT=/usr/src/certs/cert.pem
      - PUSH_KEY_PATH=/usr/src/certs/webPushKeys.json
      - NODE_ENV=production
      - DB=mongodb://admin:password@db:27017
      - PORT=80
      - SSL_PORT=443
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
      - cert-generator
    command: sh -c "yarn && npm start"

  db:
    image: mongo:latest
    container_name: cu-later-db
    restart: always
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password

volumes:
  cert:
  mongodata:
